---

- name: "Checkout repository {{ action.url }}"
  ansible.builtin.git:
    repo: "{{ action.url }}"
    dest: "{{ svc.workdir }}"
    version: "{{ action.version | default('master') }}"
    force: "{{ action.force | default(true)  }}"
    depth: "{{ action.depth | default(1)  }}"
  when: action.url is defined

- name: "Delete repository {{ action.url }}"
  file:
    path: "{{ svc.workdir }}"
    state: absent
    recurse: true
  when: svc.state == 'absent'
