---

- name: Copy file
  copy:
    src: "{{ svc.name }}/{{ action.src }}"
    dest: "{{ svc.workdir }}/{{ action.dest | default(action.src) }}"
    owner: "{{ svc.owner }}"
    group: "{{ svc.group }}"
    mode: u=rw,g=r,o=r
  when: svc.state == 'present' and action.state | default('present') == 'present'

- name: Delete file
  file:
    path: "{{ svc.workdir }}/{{ action.dest | default(action.src) }}"
    state: absent
  when:
  - svc.state == 'absent'
  - action.state | default('present') == 'absent'
