---

- set_fact:
    dir: "{{ (svc.workdir + '/' + (action.dest  | default(action.template | replace('.j2','')))) | dirname }}"
    dest: "{{ svc.workdir }}/{{ action.dest | default(action.src) }}"

- name: "Create directory {{ dir }}"
  file:
    path: "{{ dir }}"
    state: directory
    owner: "{{ svc.owner }}"
    group: "{{ svc.group }}"
    mode: u=rwx,g=rwx,o=rx
    recurse: yes

- name: "Copy file {{ dest }}"
  copy:
    src: "{{ svc.name }}/{{ action.src }}"
    dest: "{{ dest }}"
    owner: "{{ svc.owner }}"
    group: "{{ svc.group }}"
    mode: u=rw,g=r,o=r
  when: svc.state == 'present' and action.state | default('present') == 'present'

- name: Delete file
  file:
    path: "{{ dest }}"
    state: absent
  when:
  - svc.state == 'absent'
  - action.state | default('present') == 'absent'
