---

- set_fact:
    dir: "{{ svc.workdir + '/' + action.dest }}"

- name: "Create directory {{ dir }}"
  file:
    path: "{{ dir }}"
    state: directory
    owner: "{{ svc.owner }}"
    group: "{{ svc.group }}"
    mode: u=rwx,g=rwx,o=rx
    recurse: yes
