---

- name: Create directory
  file:
    path: "{{ (svc.workdir + '/' + (action.dest  | default(action.template | replace('.j2','')))) | dirname }}"
    state: directory
    owner: "{{ svc.owner }}"
    group: "{{ svc.group }}"
    mode: u=rwx,g=rwx,o=rx
    recurse: yes
