---

- name: Create directory
  file:
    path: "{{ svc.workdir + '/' + action.dest }}"
    state: directory
    owner: "{{ svc.owner }}"
    group: "{{ svc.group }}"
    mode: u=rwx,g=rwx,o=rx
    recurse: yes
