---

- name: Copy template
  template:
    src: "{{ svc.name }}/{{ action.template }}"
    dest: "{{ svc.workdir }}/{{ action.dest | default(action.template | replace('.j2','')) }}"
    owner: "{{ svc.owner }}"
    group: "{{ svc.group }}"
    mode: u=rw,g=r,o=r
  when: svc.state == 'present' and action.state | default('present') == 'present'

- name: Delete template
  file:
    path: "{{ svc.workdir }}/{{ action.dest | default(action.template | replace('.j2','')) }}"
    state: absent
  when:
  - svc.state == 'absent'
  - action.state | default('present') == 'absent'
