---

- set_fact:
    dir: "{{ (svc.workdir + '/' + (action.dest  | default(action.template | replace('.j2','')))) | dirname }}"
    templ: "{{ svc.workdir }}/{{ action.dest | default(action.template | replace('.j2','')) }}"

- name: "Create directory {{ dir }}"
  file:
    path: "{{ dir }}"
    state: directory
    owner: "{{ svc.owner }}"
    group: "{{ svc.group }}"
    mode: u=rwx,g=rwx,o=rx
    recurse: yes

- name: "Copy template {{ templ }}"
  template:
    src: "{{ svc.name }}/{{ action.template }}"
    dest: "{{ templ }}"
    owner: "{{ svc.owner }}"
    group: "{{ svc.group }}"
    mode: u=rw,g=r,o=r
  when: svc.state == 'present' and action.state | default('present') == 'present'

- name: "Delete template {{ templ }}"
  file:
    path: "{{ templ }}"
    state: absent
  when:
  - svc.state == 'absent'
  - action.state | default('present') == 'absent'
